### ISSUE TITLE
Error at uploading cell Data

### ISSUE THREAD

**Issue by ctrinker2** [openbmap/radiocells-scanner-android#211] opened 2017-10-22 13:44 UTC
What steps will reproduce the problem?
Always at updating cells data. 

What is the expected output? What do you see instead?
Uploading will start, but after a while ther stands:
"Exportfehler:
Versuch es zu einem späteren Zeitpunkt nochmal. Falls die Probleme weiter bestehen, schick uns eine Nachricht auf https://github.com/wish7code/openbmap /issues" 

And second error (alternating with the first error) :
A Exportfehler 

Versuch es zu einem späteren Zeitpunkt nochmal. Falls die Probleme weiter bestehen, schick uns eine Nachricht auf https://github.com/wish7code/openbmap /issues 

OK 

"Exportfehler 
Server nicht erreichbar. Entweder bist Du offline oder wir haben ein Server-Problem!" 

What version are you using? On what operating system?
Android 7.0 huawei p10lite emui 5.1

Please provide any additional information below.
Error exists since 2017-10-20 or 2017-10-21

**Comment by ctrinker2** [comment] 2017-10-22 13:51
I'm using radio beacon 0.8.18
error while uploading anonymous aswell as uploading with my username.

**Comment by Freso** [comment] 2017-10-25 19:21
Duplicate of https://github.com/openbmap/radiocells-scanner-android/issues/210

**Comment by wish7code** [comment] 2017-10-30 04:38
Sorry, this was a SSL related problem with certificate renewal which is fixed by now.

If problems persists, please feel free to reopen!

**Closed by wish7code** 2017-10-30 04:38 UTC

**Comment by JonnyTech** [comment] 2018-01-30 01:18
@wish7code can you please renew the certificate again

**Comment by wish7code** [comment] 2018-01-30 05:35
@JonnyTech Thanks for reminder. Should be working again..
